security:
  oauth2:
    client:
      clientId: 496107284420013
      clientSecret: 5f80defe3eac5aad90559876eb57b6e9
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAutorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: heepts://graph.facebook.com/me

